# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Guilherme Sim천es
description: >- # this means to ignore newlines until "baseurl:"
  The writings, experiments and assorted output of Guilherme Sim천es.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://guilhermesimoes.github.io" # the base hostname & protocol for your site, e.g. http://example.com
date_format: "%B %-d, %Y"
include: ["_pages"]
permalink: /blog/:title
author:
  name: Guilherme Sim천es
  given_name: Guilherme
  additional_name: Reis de Micaelo
  family_name: Sim천es
  email: guilherme.rdems@gmail.com
  uri: https://guilhermesimoes.github.io
  twitter_handle: "@glitchdout"

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-relative-links

# Plugin settings
kramdown:
  auto_ids: true

relative_links:
  collections: true

sass:
  style: compressed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
